include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart" # Drift-generated code
  language:
    strict-casts: true

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
